spring:
  datasource:
    url: jdbc:postgresql://db:5432/sampa_dev_db
    username: sampa_dev
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: sampa_dev

mapbox:
  token: pk.eyJ1IjoiZGFuaXBhc3RvY2NoaSIsImEiOiJjbWFmeHM3OTgwN3E1Mm1xNWczaGM4YWhuIn0.MHW0X8pEoalzPRoIFB6cGw
  url: https://api.mapbox.com/geocoding/v5/mapbox.places/