spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sampa_dev_db
    username: sampa_dev
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: sampa_dev
